# Code generated by protoc-gen-twirp_ruby 1.10.0, DO NOT EDIT.
require "twirp"
require_relative "haberdasher_pb"

module Twirp
  module Example
    module Haberdasher
      class HaberdasherService < ::Twirp::Service
        package "twirp.example.haberdasher"
        service "Haberdasher"
        rpc :MakeHat, Size, Hat, ruby_method: :make_hat
      end

      class HaberdasherClient < ::Twirp::Client
        client_for HaberdasherService
      end
    end
  end
end
