# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: haberdasher.proto

require 'google/protobuf'


descriptor_data = "\n\x11haberdasher.proto\x12\x19twirp.example.haberdasher\"\x16\n\x04Size\x12\x0e\n\x06inches\x18\x01 \x01(\x05\"2\n\x03Hat\x12\x0e\n\x06inches\x18\x01 \x01(\x05\x12\r\n\x05\x63olor\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t2Y\n\x0bHaberdasher\x12J\n\x07MakeHat\x12\x1f.twirp.example.haberdasher.Size\x1a\x1e.twirp.example.haberdasher.Hatb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Twirp
  module Example
    module Haberdasher
      Size = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("twirp.example.haberdasher.Size").msgclass
      Hat = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("twirp.example.haberdasher.Hat").msgclass
    end
  end
end
