# frozen_string_literal: true

# Generated by the protoc-gen-twirp_ruby gem v1.1.1. DO NOT EDIT!
# source: haberdasher.proto

require "twirp"
require_relative "haberdasher_pb"

module Twirp
  module Example
    module Haberdasher
      class HaberdasherService < ::Twirp::Service
        package "twirp.example.haberdasher"
        service "Haberdasher"
        rpc :MakeHat, Size, Hat, ruby_method: :make_hat
      end

      class HaberdasherClient < ::Twirp::Client
        client_for HaberdasherService
      end
    end
  end
end
