# frozen_string_literal: true

# Generated by the protoc-gen-twirp_ruby gem v1.1.1. DO NOT EDIT!
# source: twirp/example/cobbler/cobbler.proto

require "twirp"
require_relative "cobbler_pb"

module Twirp
  module Example
    module Cobbler
      class CobblerService < ::Twirp::Service
        package "twirp.example.cobbler"
        service "Cobbler"
        rpc :MakeShoe, Size, Shoe, ruby_method: :make_shoe
      end

      class CobblerClient < ::Twirp::Client
        client_for CobblerService
      end
    end
  end
end
