# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: twirp/example/cobbler/cobbler.proto

require 'google/protobuf'


descriptor_data = "\n#twirp/example/cobbler/cobbler.proto\x12\x15twirp.example.cobbler\"\x16\n\x04Size\x12\x0e\n\x06inches\x18\x01 \x01(\x05\"3\n\x04Shoe\x12\x0e\n\x06inches\x18\x01 \x01(\x05\x12\r\n\x05\x63olor\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t2O\n\x07\x43obbler\x12\x44\n\x08MakeShoe\x12\x1b.twirp.example.cobbler.Size\x1a\x1b.twirp.example.cobbler.Shoeb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Twirp
  module Example
    module Cobbler
      Size = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("twirp.example.cobbler.Size").msgclass
      Shoe = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("twirp.example.cobbler.Shoe").msgclass
    end
  end
end
