name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - 2.7
          - '3.0' # keep as string or it turns into "3" which pulls the newest 3.x, not 3.0.x
          - 3.1
          - 3.2
          - 3.3
          - 3.4

    env:
      RUBYOPT: --enable=frozen-string-literal

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
